ft:
	c++ -Wall -Wextra -Werror --std=c++98 main.cpp -o test_ft -I.. -O3 -fsanitize=address -g3

std:
	c++ -Wall -Wextra -Werror --std=c++98 main.cpp -o test_std -DFT_USE_STL -O3 -fsanitize=address -g3
